---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: a11y-drupal-phpmyadmin
  labels:
    app: a11y-drupal-phpmyadmin
spec:
  replicas: 0
  selector:
    matchLabels:
      app: a11y-drupal-phpmyadmin
  template:
    metadata:
      labels:
        app: a11y-drupal-phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: "a11y-drupal-mariadb"
            - name: PMA_PORT
              value: "3306"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: a11y-drupal-secret
                  key: MYSQL_ROOT_PASSWORD
