---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: a11y-drupal-mariadb
spec:
  selector:
    matchLabels:
      app: a11y-drupal-mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: a11y-drupal-mariadb
    spec:
      containers:
        - image: mariadb:10
          name: mariadb
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: a11y-drupal-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: a11y-drupal-configmap
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: a11y-drupal-configmap
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: a11y-drupal-secret
                  key: MYSQL_PASSWORD
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: a11y-drupal-mariadb-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: a11y-drupal-mariadb-persistent-storage
          persistentVolumeClaim:
            claimName: a11y-drupal-mariadb-pvc
